FROM python:3.10-slim

ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

### redis 연결 확인용 ping ###
RUN apt-get update \
    && apt-get install -y iputils-ping redis-tools \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY myproject /app/

CMD celery -A calcapp worker --loglevel=INFO