FROM python:3.10-slim

WORKDIR /app

COPY ./streamlit_app /app

RUN pip install --upgrade pip \
    && pip install streamlit \
    && pip install -r /app/requirements_streamlit.txt

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_app.py"]
