# Generated by Django 5.0 on 2024-05-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_number', models.IntegerField()),
                ('output_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
