# Generated by Django 5.0 on 2024-05-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
